spring.application.name=story-forge
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://0.0.0.0:5433/storyforge
spring.datasource.username=postgres
spring.datasource.password=devpassword
spring.jpa.hibernate.ddl-auto=update